import{a as v,S as R,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const $="53410313-8865f85a69864d0c0c63fb400",A="https://pixabay.com/api/";async function b(r,n){const c=new URLSearchParams({key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:15}),t=`${A}?${c}`;try{return(await v.get(t)).data}catch(o){throw o}}const s=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");let f;s&&(f=new R(".gallery a",{captionsData:"alt",captionDelay:250}));function L(){l&&l.removeAttribute("hidden")}function w(){l&&l.setAttribute("hidden",!0)}function S(){u&&u.removeAttribute("hidden")}function h(){u&&u.setAttribute("hidden",!0)}function P(r){if(!s)return;const n=r.map(e=>`
            <li class="gallery-item">
                <a href="${e.largeImageURL}">
                    <img src="${e.webformatURL}" alt="${e.tags}">
                </a>
                <div class="info">
                    <p><b>Likes</b> ${e.likes}</p>
                    <p><b>Views</b> ${e.views}</p>
                    <p><b>Comments</b> ${e.comments}</p>
                    <p><b>Downloads</b> ${e.downloads}</p>
                </div>
            </li>
        `).join("");s.insertAdjacentHTML("beforeend",n),f&&f.refresh()}function B(){s&&(s.innerHTML="")}const y=document.querySelector(".form");document.querySelector(".gallery");const g=document.querySelector(".load-more-btn");let i=1,m="",p=0;const M=15;function q(){i*M<p?S():(h(),p>0&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}async function E(r){r.preventDefault();const n=r.currentTarget.elements["search-text"].value.trim();if(n===""){a.error({message:"Search field cannot be empty!",position:"topRight"});return}i=1,m=n,B(),h(),L(),r.currentTarget.reset();try{const e=await b(m,i);p=e.totalHits,e.hits.length===0?a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(P(e.hits),q())}catch(e){console.error(e),a.error({title:"Error",message:"Failed to fetch images. Please check your network or API key.",position:"topRight"})}finally{w(),r.currentTarget.reset()}}async function I(){i+=1,L(),h();try{const r=await b(m,i);P(r.hits),q();const n=document.querySelector(".gallery-item");if(n){const e=n.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch(r){console.error(r),a.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),i-=1,S()}finally{w()}}y&&y.addEventListener("submit",E);g&&g.addEventListener("click",I);
//# sourceMappingURL=index.js.map
